wireservice/agate

- docs/cookbook/excel.rst
- docs/cookbook/modifying.rst
> Use NumberType instances in docs for compute function

- docs/tutorial.rst
One [code block](http://agate.readthedocs.org/en/1.1.0/tutorial.html#loading-data-from-a-csv) in the tutorial is broken.
> fix broken code block

- docs/tutorial.rst
> var agreement in lambda

- agate/preview.py
- agate/table.py
Closes #393. This function may be used for __unicode__ in Table.
> Implement the function print_structure.

- agate/tableset.py
- tests/test_tableset.py
Here's my attempt at implementing this. I turned the already implemented grouping factor using Table names into the default functionality and allow users to specify values to overwrite that. Let me know if this is or isn't what you were looking for. Closes #406.
> Implement grouping factor for TableSet.merge. Closes #406

- agate/preview.py
- agate/table.py
- agate/tableset.py
- tests/test_tableset.py
Implements TableSet.__str__. Abstracts agate.preview.print_structure for general use. Closes #418
> Implements TableSet.__str__. Closes #418

- agate/table.py
- agate/tableset.py
- examples/tableset/type_error/table1.csv
- examples/tableset/type_error/table2.csv
- tests/test_table.py
- tests/test_tableset.py
> Fix check for column_types equivalence in Table.merge and TableSet init

- agate/data_types/__init__.py
- tests/test_table.py
> Distinguish TypeTester(limit=0) from TypeTester(limit=None)

- docs/cookbook/create.rst
I took the liberty to extend the documentation to show that it is possible to send more arguments to `from_csv`. Found it searching the code. Might be useful to others too.
What do you think?
> Add documentation about the possibility to add kwargs

- agate/table.py
- tests/test_table.py
Implementation for #487. @onyxfish Also have a nagging feeling this isn't optimal but may just be residual from #495. Name change suggestions are also welcome.
> Implement Table.normalize.

- agate/utils.py
- tests/test_computations.py
> Have Quantiles.locate() return Decimal

- agate/table.py
Hi, 
I understand it's a small grammar fix but I found it as I'm learning agate (and relearning python).
> clarify definition of table method

- agate/table/order_by.py
- tests/test_table/__init__.py
Blocking https://github.com/wireservice/csvkit/pull/604
> Fix error if there is a None in the tuple when sorting

- agate/table/__init__.py
- agate/table/find.py
Hi, 
While using agate this morning and reading the docs, I found a couple small typos and fixed them.
> fix a few typos in documention

- AUTHORS.rst
- agate/table/print_table.py
- agate/utils.py
- tests/test_table/test_print_table.py
Addresses issue wireservice/agate#544
Signed-off-by: Or Sharir <or@sharir.org>
> Add a global ‘max_precision’ argument to print_table

- tutorial.ipynb
> Fix typo in tuorial

- agate/utils.py
Discovered in https://github.com/wireservice/csvkit/issues/916
> Skip NaN when calculating max_precision

- agate/data_types/date.py
To fix https://github.com/wireservice/csvkit/issues/970
> Recover from OverflowError when type testing dates

- .travis.yml
- agate/data_types/date.py
- agate/data_types/date_time.py
- requirements-py2.txt
- requirements-py3.txt
- setup.py
- tests/test_data_types.py
This PR allows to read localized dates and datetimes, with or without a date(time) format.
> Allow localization of datetimes

- agate/table/print_html.py
Simple copy/paste from print_table max_precision in print_html to prevent enlarging html  td with too much precision number
> add support print_html with max_precision

- docs/cookbook/statistics.rst
> update multiple aggregation example.
