docs/tutorial.rst

Just ran through the tutorial and came across a few small errors. Fixed 'em.
One related thing that is weird and maybe deserving of a separate issue: Putting the `agate.Formula` second in the list of computations appeared to make agate try to cast it as a decimal, which failed. I swapped the order in the tutorial to get it to work (since the same formula worked fine when it was the only list item), but seems like an issue with the type specification.
Here's a stack trace:
```python
In [51]: with_computations = exonerations.compute([
('years_in_prison', agate.Change('convicted', 'exonerated')),
('full_name', agate.Formula(text_type, lambda row: '%(first_name)s %(last_name)s' % row))
])
---------------------------------------------------------------------------
CastError …
```

Fix some syntax errors in the tutorial

---

agate/table.py
tests/test_table.py

As well as handling a filepath string, `Table.from_csv()` and `Table.to_csv()` can now handle a file-like object as the `path` parameter. Includes tests.  `TableSet.from_csv()` and `TableSet.to_csv()` remain unchanged.
This was requested in #229.

Read and write from file-like objects in Table class

---

agate/table.py
tests/test_table.py

Hello! This addresses #307.
I added a function called `Table.print_csv` that serves as a shortcut to passing `sys.stdout` to `Table.to_csv` as its `path`. Still lets you pass in `**kwargs` if a user wants to get creative with the csv formatting.
Had to mess with `StringIO` to do (what I think) is the correct way to test this. Lemme know if I went about that correctly!

Add print_csv function to Table

---

agate/data_types/base.py
tests/test_table.py

Proposed feature from Issue #344 and initial tests. Currently it only supports flat json items seperated by a new line, but it should probably be made to support a list too. May want to support nested dictionaries as well.

Implements from_json to Table method, requested feature.

---

docs/tutorial.rst

* Line 53 - Removes extra colon that prevented the code block from rendering
* Line 63 - Using example code verbatim returned ```NameError: name 'TypeTester' is not defined```. Using it as a method of agate fixes that. 
* Line 75 - Same as above.

Edits to tutorial.rst

---

agate/table.py
agate/tableset.py
examples/tableset/table1.json
examples/tableset/table2.json
examples/tableset/table3.json
tests/test_table.py
tests/test_tableset.py

Create directory if output directory does not exist for Table.to_csv and Table.to_json. Closes #392
Implement Tableset.to_json. Closes #374.
Implement Table.rename. Closes #389
Side note: sorry for the multiple commits/features and title changes. I continued working on the master branch after opening the initial pull request. I'll be sure to open feature branches from now on.

Implements TableSet.to_json, Table.rename and updates TableSet csv functions

---

agate/data_types/date.py
agate/data_types/date_time.py
tests/test_data_types.py

Implement getstate and setstate for date and date_time to handle parsedatetime pickling. Closes #362

Implement getstate and setstate to exclude parsedatetime for pickling

---

agate/table.py
tests/test_table.py

IPython, and in particular IPython/Jupyter notebooks provide rich
display of objects.  See
http://ipython.readthedocs.org/en/stable/config/integrating.html?highlight=_repr_html_#rich-display
for more information.
Implement a `agate.Table._repr_html_()` method to render the
agate Table as HTML in the notebook.
Addresses https://github.com/onyxfish/agate/issues/408

Add HTML rich display of Table instances in IPython

---

agate/table.py
tests/test_table.py

Use init instead of fork in Table.rename when column_names are changed. Include @ghing's test for row key change. Closes #423

Fixes row keys not changing on Table.rename with new column names

---

docs/cookbook/compute.rst

It fixes a small spelling mistake in the cookbook about "Compute new values"
It should be `table` instead of `tables`

Fix small spelling mistake in the documentation

---

docs/tutorial.rst

Fix trivial typo in user tutorial.
(update: added a few more)

typo: using by using -> using

---

agate/mapped_sequence.py

For #499. I think this is the kind of thing that can help newbies out. It would have helped me if I encountered the first time I was fiddling around with the app.
```python
table.rows[0][0] = 'foo'
Traceback (most recent call last):
File "example.py", line 11, in <module>
table.rows[0][0] = 'foo'
File "/home/ben/Code/agate/agate/mapped_sequence.py", line 79, in __setitem__
http://agate.readthedocs.org/en/latest/tutorial.html#computing-new-columns")
TypeError: Rows are read only and do not support item assignment. Rather that overwrite your existing data, you could create a new column based on its contents. Learn how here: http://agate.readthedocs.org/en/latest/tutorial.html#computing-new-columns
```

A more informative error message when you try to edit a row's content

---

agate/preview.py
agate/table.py
tests/test_table.py

number_formatter creation in the preview module now passes on the locale of Number objects to be more explict and try to fix the Windows bug in #453

---

docs/cookbook/compute.rst
docs/cookbook/excel.rst

Fix the documentation in a couple places by clarifying that agate.Formula() not simply Formula() is the proper way to call the function. Also, Formula requires a data type.

Clarify calling Formula, Change

---

docs/about.rst
docs/contributing.rst
docs/cookbook.rst
docs/index.rst
docs/license.rst

Tried changing up the docs wherever pages felt long/difficult to consume. Opening request in case there's a completely different way we should go about this.
(ignored api for now)

Break up docs for easier consumption

---

.gitignore
agate/table/__init__.py
tests/test_table/__init__.py

I got all tests passing in Python3.5 but tox errors out for me so I wasn't able to test in other versions of python.

Table param column_types now accepts and ordered dict

---

agate/table/pivot.py

The space means Sphinx doesn't recognise the reStructuredText markup as a table, and so it's [outputting plain text in the docs] [1] instead of an HTML table.
[1]: http://agate.readthedocs.org/en/1.3.1/api/table.html#agate.Table.pivot

Remove unneeded space in "agate.table.pivot.pivot()" docstring

---

agate/table/print_bars.py
tests/test_table/test_print_bars.py

If the value column contained null values then `agate.Table.print_bars()` would fail with `decimal.InvalidOperation` when trying to convert `None` to a decimal. Now it skips rows with null values in the value column.
If you have a table like this:
Label | Value
------------ | -------------
One | 1
A null value | 
Three | 3
And you run `table.print_bars('label', 'value')`, where previously you would see an error now you see a bar chart with two bars, one for *One*, and one for *Three*.

Print bar chart when value column contains nulls

---

agate/table/print_structure.py

Currently the ``Table`` object's ``print_structure`` method does not accept a ``max_rows`` input.
The result is that, whether you want it or not, you are stuck with a 20 row maximum because that is the default of the underlying ``print_table`` method.
I propose that this default be set to ``None``. When I explicitly type ``mytable.print_structure()`` I expect to see the entire structure, regardless of the number of fields.

set max_rows=None as the default on Table.print_structure()

---

setup.py

Related to https://github.com/wireservice/csvkit/issues/747

Bump six to the minimum version with python_2_unicode_compatible

---

docs/cookbook/sql.rst
docs/cookbook/statistics.rst

Minor fix for missing comma in docs. First two tuples in list input to the aggregate() function weren't separated by a comma.

Docs edit: Add required comma after tuple in aggregate examples

---

MANIFEST.in

For a quick context on this, I intend to package `agate` for Debian now that it is a required dependency for `csvkit`. Debian, and other Linux distributions, source themselves from PyPI and build different binary packages from it, providing modules for Python 2, Python 3 and the documentation typically.
Right now, the source tarball hosted on PyPI provides the bare minimum to build the Python binary packages, but provides neither the source for the documentation, nor the test suite necessary to ensure appropriate testing on the packaging side. This PR enhances the content of the release tarball with what Debian considers being good practice for source distribution, i.e.:
- a detailed change log
- the exact license terms
- the documentation
- the test suite
Thanks for considering this …

Improve the content of the release tarball

---

agate/data_types/date.py
agate/data_types/date_time.py
tests/test_data_types.py

Currently, if the a field contains text that can be cast to a date or datetime by parsedatetime, agate will cast the entire field to a date or datetime, even if there are other parts of the field. 
For example:
```bash
> printf "foo\n720(38-4)31A-1.1(A)" | csvlook
|                 foo |
| ------------------- |
| 2040-01-01 07:20:00 |
```
and 
```bash
> printf "COMMENT\nMC 5.7.10 Per Dorothy Carroll\ntesting workgroup fix - 4/7/2010 - Marcy Liberty" | csvlook
|    COMMENT |
| ---------- |
| 2010-05-07 |
| 2010-04-07 |
```
This PR addresses this inappropriate casting and adds tests.
Releated to https://github.com/wireservice/csvkit/issues/910 and https://github.com/wireservice/csvkit/issues/911

Be more conservative of casting text that contains dates to date and datetimes

---

.travis.yml
agate/table/print_table.py
agate/utils.py
docs/install.rst
setup.py

If `value` in `max_precision` is `Decimal('Infinity')`, then `exponent` gets set to `'F'`, causing an error. Similarly, if `v` in `print_table` is infinity, then `format_decimal` from Babel errors.

Don't calculate precision of infinity

---

docs/cookbook/locale.rst

`de_DE` is the German locale code, but the example mentions the 'Dutch locale' (whose code is `nl_NL`)

Fix locale example

---

docs/cookbook/filter.rst

Make the regex match more robust by converting the value to check to a String first, avoiding issues with NoneType or any type `re` doesn't like

Make the regex match more robust

---

MANIFEST.in

They are needed for running the tests.

Include examples in PyPI tarball

---

agate/data_types/number.py
tests/test_data_types.py

When a table has a column with only `0` and `1` as values, the agate `TypeTester` detects a `Boolean` column. If later in a script we want to merge this table with another (let's say the same dataset for another year) where the very same column has other numbers (detected as a `Number` column), we need to convert the `Boolean` column to `Number`.
To do it properly in user code, we need to write a dictionary or a function, to take into account `0`/`False`, `1`/`True` and `None`. This is tiresome and subject to errors (when users might forget `None`; also when raising exceptions which won't be agate `CastError`s in this case).
This change would allow an easy change of column type: we would just need to change the data type of the column to cast the values correctly.
This is also coherent …

Allow the conversion of booleans to numbers

---

AUTHORS.rst
agate/aggregations/max.py
agate/aggregations/min.py
agate/aggregations/sum.py
agate/computations/change.py
agate/table/pivot.py
tests/test_aggregations.py

hi! i found this a compelling issue to look at https://github.com/wireservice/csvkit/issues/1029
given i'm pretty new to open source (as well as agate), i was wondering your opinion on a few things:
1. besides running unit tests, what would you imagine would be a good testing plan here?
2. my additions broke the "pivot" unit tests in the following way (which i resolved in this PR):
```
___ TestPivot.test_pivot_sum ___
self = <tests.test_table.test_pivot.TestPivot testMethod=test_pivot_sum>
def test_pivot_sum(self):
table = Table(self.rows, self.column_names, self.column_types)
>       pivot_table = table.pivot('race', 'gender', Sum('age'))
tests/test_table/test_pivot.py:120:
_ _ _ 
agate/table/pivot.py:113: in pivot
column_type = aggregation.get_aggregate_data_type(groups)
_ _ _
self = …
```

Sum should work with time deltas, also isinstance cleanups

---

agate/table/homogenize.py

Also fixes data corruption bug due to lists being mutable.
With agate 1.6.0, default [homogenize example](http://agate.readthedocs.io/en/1.6.0/cookbook/homogenize.html):
```
>>> table.homogenize('year', range(1997, 2003), (0, 0))
AttributeError: 'tuple' object has no attribute 'insert'
>>> table.homogenize('year', range(1997, 2003), [0, 0])
(('year', Decimal('1997')), ('f', Decimal('2')), ('m', Decimal('1')))
(('year', Decimal('2000')), ('f', Decimal('4')), ('m', Decimal('3')))
(('year', Decimal('2002')), ('f', Decimal('4')), ('m', Decimal('5')))
(('year', Decimal('2003')), ('f', Decimal('1')), ('m', Decimal('2')))
(('year', 1999), ('f', 0), ('m', 0))
(('year', 1998), ('f', 1999), ('m', 0))
(('year', 2001), ('f', 1998), ('m', 1999))
```
With fix (for both tuples and list arguments):
``` …
```

Fix homogenize not working with tuples

---

agate/aggregations/mean.py
tests/test_aggregations.py

When processing data, sometimes you end up with a column of null values.  If this is then pushed into a pipeline of operations which include calculating the mean on that column, then the whole process errors out.  
I've opted to return None in these situations.  Originally, I planned to return '0' feeling it would be more in keeping with the expected data type from the mean operation.  However, upon reflection, I think this would be a mistake as if the column normally contains '0' and '1' then it might be confusing and misleading.

Fix divide by zero when calculating Means

---

agate/table/join.py

There is a small typo in agate/table/join.py.
Should read `perform` rather than `peform`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, peform -> perform

---

CHANGELOG.rst
agate/data_types/date_time.py
docs/cookbook/datetime.rst
setup.py
tests/test_data_types.py

Starting with Python 3.9 a zoneinfo package is available in the standard library for this feature. There is therefore no need for this dependency and a compatibility layer is available at
https://pypi.org/project/backports.zoneinfo/ for older Python versions.
I made this change because agate is packaged in Fedora and Fedora is deprecating pytz: https://fedoraproject.org/wiki/Changes/DeprecatePytz

Remove dependency on pytz

---

AUTHORS.rst
agate/table/print_table.py
tests/test_table/test_print_table.py

closes #749 
Replaces `\n` with `↵` to keep the output of `print_table` readable. Added a test to `test_print_table.py`.

Replace newline characters in print_table()
